# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      actions: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: echo "Github Workspace - ${{ github.workspace }}"
      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
      - name: Run Unit Tests
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
      - run: ls  ${{ github.workspace }}/build/meson-logs/
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/meson-logs/*
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./**/build/meson-logs/*.junit.xml
